### ISSUE TITLE
telemetry-key-prefix-mobile-event-dailyUploadCount is larger than limit

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/telemetry-ios#96] opened 2018-04-19 00:59 UTC
Probably related to #95. I grabbed Fennec's App Container and when I look in the preferences.plist, I see this:

```
telemetry-key-prefix-mobile-event-dailyUploadCount: 103
telemetry-key-prefix-core-dailyUploadCount: 103
```

This should not be possible since `MaxNumberOfPingUploadsPerDay` is set to `100`.

**Comment by justindarc** [comment] 2018-04-19 17:50
This is also a dupe of #94. When a day passes since the last ping was sent, at least one ping will get uploaded. Afterwards, we'll increment the upload count before checking if we've exceeded the `MaxNumberOfPingUploadsPerDay` threshold. This is how that value is exceeding the threshold (it is not checked until after the first ping is uploaded).

**Closed by justindarc** 2018-04-19 17:50 UTC
